:toc: left
:toclevels: 4
:sectnums:

= docker-base dockerimages

A repository az icellmobilsoft-ban használt base docker image-k gyűjtését szolgálja,
hogy azonos alapon működjenek a projektek és azok buildjei. 

A projekt részeit több részre osztható,
egymást kiegészítik.
Alapvetően 2 csoportja oszthatóak az image-k:

* *parent (base image)* - ezek azok az docker imagek,
melyeket a cél termékeknél base image-nek használunk.
Csak a feltétlenül szükséges funkció és tartalom lehet bennük.
* *builder* - tartalom hordozásra használjuk őket,
sosem szabad base image-re használni.
A funkciója a multi-stage dockerfile-ban van,
ahol például driver tárhelyként van felhasználva.

== Projekt struktúra

=== /dockerfile
Maga a dockerfile-ok gyűjtője.
Részletes leírása a létrehozott docker image-ről a FIXME[Docker Base Images] címen olvasható.

=== /script
Általános scriptek, melyeket a dockerimage-k is felhasználnak,
de használhatóak önmagukban is.

== Fejlesztés
Mindent amit ehhez tudni kell az a következő parancs:

[source,bash]
----
docker-compose -f <PATH>/docker-base/docker-compose.yml build
----
[IMPORTANT]
====
A release és docker push parancsot kizárólag a Github Actions-re kell bízni! 
====

== Release
A release készítése Github Actions végzi.
Alapvetően 2 esetet kezelünk:

. *Major verzió* - Fő verzió release, csak a *master branchből* keletkezhet.
. *Minor verzió* - Bugfix verzió, csak *release branchből* keletkezhet.

A hozzátartozó CI csak a megfelelő brancheknél jelenik meg.

A Gitlab CI lépései:

. docker-compose.yml build parancs futtatása
. `ci/release/release.sh` script futása, ami a következőket műveli:
.. `.env` fájl importja
.. `:latest` tag létrehozása
.. `docker push` minden image és tag-re
