:toc: left
:toclevels: 4
:sectnums:

= docker-base dockerimages

The repository serves to collect the base Docker images used in icellmobilsoft so that the projects and their builds operate on a common basis.

he parts of the project can be divided into multiple sections, complementing each other.
The images can basically be divided into 2 groups:

* *bases* - These are the Docker images we use as base images for the target products. They can only contain the absolutely necessary functions and content.
* *builder* - We use them for content delivery, and they should not be used as base images. Their function is for building, compiling, in multi-stage Dockerfiles, or even for GitLab runner usage.

== Project Structure

=== /dockerfile
It serves as a collector of Dockerfiles.
The detailed description of the created Docker image can be found under the title FIXME[Docker Base Images].

=== /script
General scripts used by Docker images, but also usable standalone.

== Development
All you need to know for this is the following command:

[source,bash]
----
docker-compose -f <PATH>/docker-base/docker-compose.yml build
----
[IMPORTANT]
====
The release and docker push commands should be exclusively handled by GitHub Actions!
====

== Release
Creating releases is handled by GitHub Actions.
We basically handle 2 cases:

. *Major, Minor version* - main version release, can only originate from the *master branch*.
. *Bugfix version* - can only originate from a *release branch*.

The corresponding CI appears only on the appropriate branches.

