#!/usr/bin/env bash

set -e;

echo "NEXUS_OBJECT_GROUP_ID=$NEXUS_OBJECT_GROUP_ID"
echo "NEXUS_OBJECT_ARTIFACT_ID=$NEXUS_OBJECT_ARTIFACT_ID"
echo "NEXUS_OBJECT_VERSION=$NEXUS_OBJECT_VERSION"
echo "NEXUS_OBJECT_CLASSIFIER=$NEXUS_OBJECT_CLASSIFIER"
NEXUS_OBJECT_EXTENSION=${NEXUS_OBJECT_EXTENSION:-jar}
echo "NEXUS_OBJECT_EXTENSION=$NEXUS_OBJECT_EXTENSION"

if [ -z "$NEXUS_OBJECT_CLASSIFIER" ]; then
    # we are looking for empty classifiers by default
    PATH_PARAM_CLASSIFIER=""
else
    PATH_PARAM_CLASSIFIER="-$NEXUS_OBJECT_CLASSIFIER"
fi

NEXUS_DOWNLOAD_OUTPUT_FILE_NAME=${NEXUS_DOWNLOAD_OUTPUT_FILE_NAME:-"$NEXUS_OBJECT_ARTIFACT_ID-$NEXUS_OBJECT_VERSION$PATH_PARAM_CLASSIFIER.$NEXUS_OBJECT_EXTENSION"}
NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1=${NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1:-"$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME.sha1"}
echo "NEXUS_DOWNLOAD_OUTPUT_FILE_NAME=$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME"
echo "NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1=$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1"

GROUP_PATH="${NEXUS_OBJECT_GROUP_ID//.//}"
OBJECT_PATH="$GROUP_PATH/$NEXUS_OBJECT_ARTIFACT_ID/$NEXUS_OBJECT_VERSION/$NEXUS_OBJECT_ARTIFACT_ID-$NEXUS_OBJECT_VERSION$PATH_PARAM_CLASSIFIER.$NEXUS_OBJECT_EXTENSION"
OBJECT_PATH_SHA1="$GROUP_PATH/$NEXUS_OBJECT_ARTIFACT_ID/$NEXUS_OBJECT_VERSION/$NEXUS_OBJECT_ARTIFACT_ID-$NEXUS_OBJECT_VERSION$PATH_PARAM_CLASSIFIER.$NEXUS_OBJECT_EXTENSION.sha1"
#https://central.sonatype.org/search/example-urls/
MAVEN_SEARCH_API="https://search.maven.org/remotecontent?filepath="

curl -L -X GET $MAVEN_SEARCH_API$OBJECT_PATH --output $NEXUS_DOWNLOAD_OUTPUT_FILE_NAME;
curl -L -X GET $MAVEN_SEARCH_API$OBJECT_PATH_SHA1 --output $NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1;
FILE_SIZE=$(stat -c%s "$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME")
SHA1_FILE_SIZE=$(stat -c%s "$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1")
echo "$PWD/$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME file downloaded, size: $FILE_SIZE bytes."
echo "$PWD/$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1 file downloaded, size: $SHA1_FILE_SIZE bytes."

# checksum
SHA1_ORIGINAL=$(cat $DOWNLOAD_DIR/$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1);
SHA1_FILE=$(sha1sum $DOWNLOAD_DIR/$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME | awk '{print $1}')
if [ "$SHA1_ORIGINAL" = "$SHA1_FILE" ]; then
    echo "Checksum OK"
else
    echo "Corrupted file!"
    exit 1
fi