= v1.4.0

All images are 1:1 compatible with version 1.3.0.

.Changes
* The *icellmobilsoft/builder-nexus-download* builder image has changed:
** Starting from this version, the environment variable NEXUS_OBJECT_CLASSIFIER is also used by the images.
** Improvement in resolving NEXUS_OBJECT_GROUP if it contains a dot (`.`) in the artifact groupId
** Enhancing sonatype-download.sh script with handling of SONATYPE_URL and SONATYPE_REPOSITORY environment variables

* The *icellmobilsoft/builder-nexus-download* builder image has changed:
* In the case of Curl, URLs are now enclosed in double quotes to prevent the runtime environment from attempting to evaluate the download address. This fix has been added to all shell scripts.

* bump base image alpine:3.18.4 -> alpine:3.18.5
* Component upgrade:
** Java 11.0.20.1_1-jre -> 11.0.21_9-jre
** Java 11.0.20.1_1-jdk -> 11.0.21_9-jdk
** Java 17.0.8.1_1-jre -> 17.0.9_9-jre
** Java 17.0.8.1_1-jdk -> 17.0.9_9-jdk
** Java 21_35-jre -> 21.0.1_12-jre
** Java 21_35-jdk -> 21.0.1_12-jdk
** Galleon 5.1.0.Final -> 5.2.1.Final
