= alpine-runner

* Image: `icellmobilsoft/builder-alpine-runner`
* Base: `icellmobilsoft/base-alpine`
* Purpose: A base image containing a toolset for various stages of development
* Used *argument*:
** *BASE_IMAGE* - Specifies the base image, it has no default value
** *USER_GID* - The GID (Group ID) of the created user group (default `101`)
** *USER_UID* - The UID (User ID) of the created user (default `101`)
** *SYSTEM_USER_DEFAULT* - The name of the created user (default `icellmobilsoft`)
** *SYSTEM_USER_GROUP_DEFAULT* - The name of the created user group (default `icellmobilsoft`)
** *$SYSTEM_USER* - Non 'root' user with which the image runs (default: `icellmobilsoft`)
** *$SYSTEM_USER_GROUP* - The Linux group of the SYSTEM_USER (default: `icellmobilsoft`)
** *$HOME* - The home directory of the SYSTEM_USER (WORKDIR $HOME)
* Installed programs:
** *bash*
** *git*
** *openssh*
** *curl*
** *libxml2-utils*
** *jq*

= builder/java8-maven

* Image: `icellmobilsoft/builder-java8-maven`
* Base: `icellmobilsoft/base-curl`
* Purpose: Building a project with Maven based on Java 8 foundations
* Used *argument*:
** *BASE_IMAGE* - Specifies the base image, it has no default value
** *JRE_TEMURIN_IMAGE* - A Temurin Java image, from which the JRE parts are copied into the final image
** *DOWNLOAD_DIR_DEFAULT* - Default download directory (where the Maven tar.gz is downloaded) (default: `$HOME/download = /home/icellmobilsoft/download`)
** *SHA* - SHA of the Maven file to be downloaded (default: `SHA of the current version from the website`)
** *MAVEN_DOWNLOAD_URL* - Donwload URl of Maven (default: `https://archive.apache.org/dist/maven/maven-3/${MAVEN_OLD_VERSION}/binaries`)
* Added *ENV*:
** *MAVEN_VERSION* - Version number of the Maven used
** *DOWNLOAD_DIR* - Used in scripts (default `$DOWNLOAD_DIR_DEFAULT$`)
** *MAVEN_HOME* - Environment variable of MAVEN_HOME for Maven (default `$HOME/maven=/home/icellmobilsoft/maven`)
** *MAVEN_CONFIG* - Maven configuration (default `$HOME/.m2=/home/icellmobilsoft/.m2`)
* Installed programs:
** *maven* - Extracted into $MAVEN_HOME
** *jdk* - Extracted into /opt/java/openjdk
** *git*
** *libxml2-utils*
** *jq*

= builder/java11-maven

* Image: `icellmobilsoft/builder-java11-maven`
* Base: `icellmobilsoft/base-curl`
* Purpose: Building a project with Maven based on Java 11 foundations
* Used *argument*:
** *BASE_IMAGE* - Specifies the base image, it has no default value
** *JRE_TEMURIN_IMAGE* - A Temurin Java image, from which the JRE parts are copied into the final image
** *DOWNLOAD_DIR_DEFAULT* - Default download directory (where the Maven tar.gz is downloaded) (default: `$HOME/download = /home/icellmobilsoft/download`)
** *SHA* - SHA of the Maven file to be downloaded (default: `SHA of the current version from the website`)
** *MAVEN_DOWNLOAD_URL* - Donwload URl of Maven (default: `https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries`)
* Added *ENV*:
** *MAVEN_VERSION* - Version number of the Maven used
** *DOWNLOAD_DIR* - Used in scripts (default `$DOWNLOAD_DIR_DEFAULT$`)
** *MAVEN_HOME* - Environment variable of MAVEN_HOME for Maven (default `$HOME/maven=/home/icellmobilsoft/maven`)
** *MAVEN_CONFIG* - Maven configuration (default `$HOME/.m2=/home/icellmobilsoft/.m2`)
* Installed programs:
** *maven* - Extracted into $MAVEN_HOME
** *jdk* - Extracted into /opt/java/openjdk 
** *git*
** *libxml2-utils*
** *jq*

= builder/java17-maven

* Image: `icellmobilsoft/builder-java17-maven`
* Base: `icellmobilsoft/base-curl`
* Purpose: Building a project with Maven based on Java 17 foundations
* Used *argument*:
** *BASE_IMAGE* - Specifies the base image, it has no default value
** *JRE_TEMURIN_IMAGE* - A Temurin Java image, from which the JRE parts are copied into the final image
** *DOWNLOAD_DIR_DEFAULT* - Default download directory (where the Maven tar.gz is downloaded) (default: `$HOME/download = /home/icellmobilsoft/download`)
** *SHA* - SHA of the Maven file to be downloaded (default: `SHA of the current version from the website`)
** *MAVEN_DOWNLOAD_URL* - Donwload URl of Maven (default: `https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries`)
* Added *ENV*:
** *MAVEN_VERSION* - Version number of the Maven used
** *DOWNLOAD_DIR* - Used in scripts (default `$DOWNLOAD_DIR_DEFAULT$`)
** *MAVEN_HOME* - Environment variable of MAVEN_HOME for Maven (default `$HOME/maven=/home/icellmobilsoft/maven`)
** *MAVEN_CONFIG* - Maven configuration (default `$HOME/.m2=/home/icellmobilsoft/.m2`)
* Installed programs:
** *maven* - Extracted into $MAVEN_HOME
** *jdk* - Extracted into /opt/java/openjdk 
** *git*
** *libxml2-utils*
** *jq*

= builder/java21-maven

* Image: `icellmobilsoft/builder-java21-maven`
* Base: `icellmobilsoft/base-curl`
* Purpose: Building a project with Maven based on Java 21 foundations
* Used *argument*:
** *BASE_IMAGE* - Specifies the base image, it has no default value
** *JRE_TEMURIN_IMAGE* - A Temurin Java image, from which the JRE parts are copied into the final image
** *DOWNLOAD_DIR_DEFAULT* - Default download directory (where the Maven tar.gz is downloaded) (default: `$HOME/download = /home/icellmobilsoft/download`)
** *SHA* - SHA of the Maven file to be downloaded (default: `SHA of the current version from the website`)
** *MAVEN_DOWNLOAD_URL* - Donwload URl of Maven (default: `https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries`)
* Added *ENV*:
** *MAVEN_VERSION* - Version number of the Maven used
** *DOWNLOAD_DIR* - Used in scripts (default `$DOWNLOAD_DIR_DEFAULT$`)
** *MAVEN_HOME* - Environment variable of MAVEN_HOME for Maven (default `$HOME/maven=/home/icellmobilsoft/maven`)
** *MAVEN_CONFIG* - Maven configuration (default `$HOME/.m2=/home/icellmobilsoft/.m2`)
* Installed programs:
** *maven* - Extracted into $MAVEN_HOME
** *jdk* - Extracted into /opt/java/openjdk 
** *git*
** *libxml2-utils*
** *jq*

= builder/java8-galleon

* Image: `icellmobilsoft/builder-java8-galleon`
* Base: `icellmobilsoft/builder-java8-maven`
* Purpose: Building WildFly with Galleon using Maven support on Java 8 foundations
* Used *argument*:
** *BASE_BUILDER_IMAGE* - Specifies the base image, it has no default value
** *GALLEON_VERSION* - Version number of Galleon
** *DOWNLOAD_DIR_DEFAULT* - Default download directory (where the Maven tar.gz is downloaded) (default: `$HOME/download = /home/icellmobilsoft/download`)
* Added *ENV*:
** *GALLEON_HOME* - Directory of Galleon (default `$HOME/galleon=/home/icellmobilsoft/galleon`)
** *GALLEON_VERSION* - Used in scripts (default `GALLEON_VERSION` argumentum)
** *DOWNLOAD_DIR* - Download directory where Galleon will be downloaded (default `$HOME/download=/home/icellmobilsoft/download`)
* Installed programs:
** *galleon* - Extracted into $GALLEON_HOME

= builder/java11-galleon

* Image: `icellmobilsoft/builder-java11-galleon`
* Base: `icellmobilsoft/builder-java11-maven`
* Purpose: Building WildFly with Galleon using Maven support on Java 11 foundations
* Used *argument*:
** *BASE_BUILDER_IMAGE* - Specifies the base image, it has no default value
** *GALLEON_VERSION* - Version number of Galleon
** *DOWNLOAD_DIR_DEFAULT* - Default download directory (where the Maven tar.gz is downloaded) (default: `$HOME/download = /home/icellmobilsoft/download`)
* Added *ENV*:
** *GALLEON_HOME* - Directory of Galleon (default `$HOME/galleon=/home/icellmobilsoft/galleon`)
** *GALLEON_VERSION* - Used in scripts (default `GALLEON_VERSION` argumentum)
** *DOWNLOAD_DIR* - Download directory where Galleon will be downloaded (default `$HOME/download=/home/icellmobilsoft/download`)
* Installed programs:
** *galleon* - Extracted into $GALLEON_HOME

= builder/java17-galleon

* Image: `icellmobilsoft/builder-java17-galleon`
* Base: `icellmobilsoft/builder-java17-maven`
* Purpose: Building WildFly with Galleon using Maven support on Java 17 foundations
* Used *argument*:
** *BASE_BUILDER_IMAGE* - Specifies the base image, it has no default value
** *GALLEON_VERSION* - Version number of Galleon
** *DOWNLOAD_DIR_DEFAULT* - Default download directory (where the Maven tar.gz is downloaded) (default: `$HOME/download = /home/icellmobilsoft/download`)
* Added *ENV*:
** *GALLEON_HOME* - Directory of Galleon (default `$HOME/galleon=/home/icellmobilsoft/galleon`)
** *GALLEON_VERSION* - Used in scripts (default `GALLEON_VERSION` argumentum)
** *DOWNLOAD_DIR* - Download directory where Galleon will be downloaded (default `$HOME/download=/home/icellmobilsoft/download`)
* Installed programs:
** *galleon* - Extracted into $GALLEON_HOME

= builder/java21-galleon

* Image: `icellmobilsoft/builder-java21-galleon`
* Base: `icellmobilsoft/builder-java21-maven`
* Purpose: Building WildFly with Galleon using Maven support on Java 21 foundations
* Used *argument*:
** *BASE_BUILDER_IMAGE* - Specifies the base image, it has no default value
** *GALLEON_VERSION* - Version number of Galleon
** *DOWNLOAD_DIR_DEFAULT* - Default download directory (where the Maven tar.gz is downloaded) (default: `$HOME/download = /home/icellmobilsoft/download`)
* Added *ENV*:
** *GALLEON_HOME* - Directory of Galleon (default `$HOME/galleon=/home/icellmobilsoft/galleon`)
** *GALLEON_VERSION* - Used in scripts (default `GALLEON_VERSION` argumentum)
** *DOWNLOAD_DIR* - Download directory where Galleon will be downloaded (default `$HOME/download=/home/icellmobilsoft/download`)
* Installed programs:
** *galleon* - Extracted into $GALLEON_HOME

= builder/nexus-download

* Image: `icellmobilsoft/builder-nexus-download`
* Base: `icellmobilsoft/base-curl`
* Purpose: Downloading artifacts from the company's Nexus or central repository
* Used *argument*:
** *BASE_BUILDER_IMAGE* - Specifies the base image, it has no default value
** *DOWNLOAD_DIR_DEFAULT* - Default download directory (where the Maven tar.gz is downloaded) (default: `$HOME/download = /home/icellmobilsoft/download`)
** *NEXUS_USER* - Nexus user
** *NEXUS_PASSWORD* - Nexus user password (plain text)
** *NEXUS_REPOSITORY_URL* - Nexus repository url
** *NEXUS_REPOSITORY* - Nexus repository within Nexus (e.g.: public)
** *NEXUS_OBJECT_GROUP_ID* - The groupId of the artifact object
** *NEXUS_OBJECT_ARTIFACT_ID* - The artifact of the artifact object
** *NEXUS_OBJECT_EXTENSION* - The extension of the artifact object (e.g.: jar)
** *NEXUS_OBJECT_VERSION* - The version of the artifact object
** *NEXUS_OBJECT_CLASSIFIER* - The classifier of the artifact object
** *NEXUS_DOWNLOAD_OUTPUT_FILE_NAME* - Output name of the file to be downloaded
** *NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1* - SHA1 of the file to be downloaded
** *SONATYPE_URL* - Sonatype base url (default `https://oss.sonatype.org`) 
** *SONATYPE_REPOSITORY* - The name of the repository from which we want to download the file (default `releases`) 
* Added *ENV*:
** *DOWNLOAD_DIR* - Download directory where Galleon will be downloaded (default `$HOME/download=/home/icellmobilsoft/download`)
** *NEXUS_USER* - Nexus username from argument (default `$NEXUS_USER`)
** *NEXUS_PASSWORD* - Nexus user password from argument (default `$NEXUS_PASSWORD`)
** *NEXUS_REPOSITORY_URL* - Nexus repository URL from argument (default `$NEXUS_REPOSITORY_URL`)
** *NEXUS_REPOSITORY* - Nexus repository within Nexus from argument (default `$NEXUS_REPOSITORY`)
** *NEXUS_OBJECT_GROUP_ID* - Artifact object's groupId from argument (default `$NEXUS_OBJECT_GROUP_ID`)
** *NEXUS_OBJECT_ARTIFACT_ID* - AArtifact object's artifactId from argument (default `$NEXUS_OBJECT_ARTIFACT_ID`)
** *NEXUS_OBJECT_EXTENSION* - Artifact object's extension from argument (default `$NEXUS_OBJECT_EXTENSION`)
** *NEXUS_OBJECT_VERSION* - Artifact object's version from argument (default `$NEXUS_OBJECT_VERSION`)
** *NEXUS_OBJECT_CLASSIFIER* - Artifacet objektum classifier from argument (default `$NEXUS_OBJECT_CLASSIFIER`)
** *NEXUS_DOWNLOAD_OUTPUT_FILE_NAME* - Output name of the file to be downloaded from argument (default `$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME`)
** *NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1* - SHA1 of the file to be downloaded from argument (default `$NEXUS_DOWNLOAD_OUTPUT_FILE_NAME_SHA1`)
** *SONATYPE_URL* - Sonatype base url (default `https://oss.sonatype.org`) 
** *SONATYPE_REPOSITORY* - The name of the repository from which we want to download the file (default `releases`) 
* Installed programs: -

NOTE: The downloaded artifact will be located in the DOWNLOAD_DIR.

